article/urls.py
# 引入path
from django.urls import path

# 正在部署的应用名称
app_name = 'article'

from . import views

urlpatterns = [
    #将url映射到view
    path('detail_<int:id>/',views.article,name='article_detail'),
    path('',views.index,name='article'),
]

blog/urls.py
from django.contrib import admin
from django.urls import path,include

from article import views

urlpatterns = [
    path('admin/',admin.site.urls),
    path('mdeditor/',include('mdeditor.urls')),
    #配置应用urls
    path('article/',include('article.urls',namespace='article')),
    #配置index初始页urls
    path('',views.index,name='index'),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    # static files (images, css, javascript, etc.)主要是让页面显示正常
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_DIRS)

article/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User
# timezone 用于处理时间相关事务。
from django.utils import timezone
from mdeditor.fields import MDTextField

#文章数据模型
class Article(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE,verbose_name='作者',default=User)
    title=models.CharField('标题',max_length=60)
    summary=models.TextField('摘要',max_length=200,blank=True)
    body=MDTextField(verbose_name='正文')
    #background=models.ImageField(upload_to='article_img/%Y/%m/%d/', verbose_name='文章图片', blank=True, null=True)
    views=models.PositiveIntegerField('阅读量', default=0)
    created=models.DateTimeField('创建时间', default=timezone.now)
    updated=models.DateTimeField('更新时间', auto_now=True)
    #元数据定义
    class Meta:
        ordering=['-created']   #数据返回顺序：依照created倒序排列
    #模型类调用定义
    def __str__(self):
        return self.title       #返回对象属性title

article/views.py
from django.shortcuts import render

# Create your views here.

from .models import Article

def index(request):
    #取出所有文章
    articles=Article.objects.all()
    #需要传递给模板（templates）的对象
    context={'articles':articles }
    #render函数：载入模板，并返回context对象
    return render(request,'index.html',context)

import markdown

def article(request,id):
    #取出相应文章
    article=Article.objects.get(id=id)
    #markdown渲染
    article.body=markdown.markdown(article.body,
        extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            'markdown.extensions.toc',
        ])
    context={'article':article}
    return render(request,'article/detail.html',context)

templates/article/detail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'mdeditor/style/monokai.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'article/css/content.css' %}">
</head>
<body>
    <!--header-->
    {% include 'index/header.html' %}
    <!--content-->
    <div class="content">
        <div class="card">
            <div class="card_file">
                <span>{{article.body|safe}}</span>
            </div>
        </div>
    </div>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Silke's Blog</title>
    <link href="https://cdn.bootcdn.net/ajax/libs/font-awesome/6.3.0/css/all.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'index/css/global.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/header.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/content.css' %}">
    <link rel="stylesheet" href="{% static 'index/css/footer.css' %}">
</head>
<body>
    <!--header-->
    {% include 'index/header.html' %}
    <!--content-->
    <div class="content">   
        {%for i in articles %}
            <div class="card">
                {%if forloop.counter|divisibleby:2 %}
                <div class="card_image" style="border-radius: 32px 0px 0px 32px"></div>
                <div class="card_file" style="border-radius: 0px 32px 32px 0px">
                {% endif %}
                {%if forloop.counter0|divisibleby:2 %}
                <div class="card_file">
                {% endif %}
                    <div id="file_data"><i class="fa far fa-clock"></i>{{ i.created }}</div>
                    <div id="file_head">
                        <a href="{% url 'article:article_detail' i.id %}#sticky"><span>标题:{{ i.title }}</span></a>
                    </div>
                    <div id="file_meta">
                        <i class="fas fa-eye"></i><span> {{ i.views }} </span>
                        <i class="fas fa-pencil-alt"></i><span> {{ i.author }} </span>
                    </div>
                    <div id="file_show">
                        <span>摘要:{{ i.summary }}</span>
                    </div>
                    <div id="file_option">
                        <i class="fas far fa-edit"></i><span> </span>
                        <i class="fas far fa-trash-alt"></i><span></span>
                    </div>
                </div>
                {%if forloop.counter0|divisibleby:2 %}
                <div class="card_image"></div>
                {% endif %}
            </div>
        {% endfor %}
    </div>
    <!--footer-->
</body>
</html>

templates/index/header.html
{% load static %}
<div class="header">
    <div class="navbar_top">
        <div id="search">
            <button type="submit"><i class="fa fa-search"></i></button>
            <input type="text" placeholder="search...">
        </div>
        <div id="navblock">
            <ul>
                <li><a href="{% url 'index' %}"><i class="fa fa-home"></i>首页</a></li>
                <li id="envelope_drop">
                    <a href="###"><i class="fa fa-envelope"></i>联系</a>
                    <div id="envelope_hide">
                        <a href="###"><i class="fab fa-qq"></i>QQ</a>
                        <a href="https://space.bilibili.com/3493137005676846"><i class="fab fa-bilibili"></i>B站</a>
                    </div>
                </li>
                <li id="link_drop">
                    <a href="###"><i class="fa fa-link"></i>关于</a>
                    <div id="link_hide">
                        <a href="###">v我50</a>
                        <a href="###">٩(ˊωˋ*)و</a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="background">
        <canvas id="matrix"></canvas>
        <script src="{% static 'index/js/matrix.js' %}"></script>
    </div>
    <div class="background_block">
        <h1>Silke's Blog</h1>
    </div>
    <div class="navbar_bottom" id="sticky">
        <ul>
            <li id="cloud_drop">
                <a href="###"><i class="fa fa-cloud"></i>仓库</a>
                <div id="cloud_hide">
                    <a href="###">图片</a>
                    <a href="###">文档</a>
                    <a href="###">实验室</a>
                </div>
            </li>
            <li id="cog_drop">
                <a href="/admin"><i class="fa fa-cog"></i>后台</a>
            </li>
            <li id="book_drop">
                <a href="{% url 'article:article' %}#sticky"><i class="fa fa-book"></i>随笔</a>
            </li>
        </ul>
    </div>
    <script src="{% static 'index/js/sticky.js' %}"></script>
</div>